name: Compile Typst docs
on: [push, workflow_dispatch]

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install typst CLI
              run: |
                  mkdir -p $HOME/.local/bin
                  echo $HOME/.local/bin >> $GITHUB_PATH
                  wget https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz -O /tmp/typst-x86_64-unknown-linux-musl.tar.xz
                  tar xf /tmp/typst-x86_64-unknown-linux-musl.tar.xz -C $HOME/.local/bin --strip-components=1 typst-x86_64-unknown-linux-musl/typst

            - name: Install Noto Sans font
              run: |
                  mkdir -p $HOME/.local/share/fonts
                  wget https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip -O /tmp/NotoSans-unhinted.zip
                  unzip /tmp/NotoSans-unhinted.zip -d $HOME/.local/share/fonts
                  fc-cache -f -v
            
            - name: Install JetBrains Mono font
              run: |
                mkdir -p $HOME/.local/share/fonts
                wget https://download.jetbrains.com/fonts/JetBrainsMono-2.242.zip -O /tmp/JetBrainsMono.zip
                unzip /tmp/JetBrainsMono.zip -d $HOME/.local/share/fonts
                fc-cache -f -v

            - name: Find and compile Typst files
              run: |
                  find . -path ./template -prune -o -name "*.typ" -print0 | while IFS= read -r -d '' file; do
                    typst compile --root . "$file" "${file%.typ}.pdf" --font-path $HOME/.local/share/fonts
                  done

            - name: Move PDF files to parent directory
              run: |
                  find . -name "*.pdf" -exec sh -c 'mv "$0" "$(dirname "$0")/../"' {} \;

            - name: Upload PDF files
              uses: actions/upload-artifact@v4
              with:
                  name: Documentazione-CodeHex16
                  path: "**/*.pdf"

            - name: Commit and push PDF files
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add '**/*.pdf'
                  git commit -m 'Add compiled PDF files'
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
