name: Compile Typst Check
on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ssh-key: ${{secrets.DEPLOY_KEY}}

            - name: Install typst CLI
              run: |
                  mkdir -p $HOME/.local/bin
                  echo $HOME/.local/bin >> $GITHUB_PATH
                  wget https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz -O /tmp/typst-x86_64-unknown-linux-musl.tar.xz
                  tar xf /tmp/typst-x86_64-unknown-linux-musl.tar.xz -C $HOME/.local/bin --strip-components=1 typst-x86_64-unknown-linux-musl/typst

            - name: Install Noto Sans font
              run: |
                  mkdir -p $HOME/.local/share/fonts
                  wget https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip -O /tmp/NotoSans-unhinted.zip
                  unzip /tmp/NotoSans-unhinted.zip -d $HOME/.local/share/fonts
                  fc-cache -f -v

            - name: Install JetBrains Mono font
              run: |
                  wget https://download.jetbrains.com/fonts/JetBrainsMono-2.242.zip -O /tmp/JetBrainsMono.zip
                  unzip /tmp/JetBrainsMono.zip -d $HOME/.local/share/fonts
                  fc-cache -f -v

            - name: Aggiungi \#gloss[...] ai termini trovati nei file .typ
              run: |
                  cd glossario/source
                  python glossario.py
                  cd ../..

            - name: Find and compile Typst files
              run: |
                  find . -path ./template -prune -o -name "*.typ" -print0 | while IFS= read -r -d '' file; do
                    typst compile --root . "$file" "${file%.typ}.pdf" --font-path $HOME/.local/share/fonts
                  done